```python
import unittest
import time
import uuid
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class UserRegistrationTest(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        self.driver.maximize_window()
        self.url = "http://localhost:8000/dk"
        self.html_data = {
          "home_page": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div><div><span><h1>Ecommerce Starter Template</h1><h2>Powered by Medusa and Next.js</h2></span><a href=\"https://github.com/medusajs/nextjs-starter-medusa\"><button>View on GitHub<svg><path></path></svg></button></a></div></div><footer><div><div><div><div><a href=\"/dk\">Medusa Store</a></div><div><div><span>Categories</span><ul data-testid=\"footer-categories\"><li><a data-testid=\"category-link\" href=\"/dk/categories/sweatshirts\">Sweatshirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/shirts\">Shirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/pants\">Pants</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/merch\">Merch</a><ul></ul></li></ul></div><div><span>Medusa</span><ul><li><a href=\"https://github.com/medusajs\">GitHub</a></li><li><a href=\"https://docs.medusajs.com\">Documentation</a></li><li><a href=\"https://github.com/medusajs/nextjs-starter-medusa\">Source code</a></li></ul></div></div></div><div><p>\u00a9 2025 Medusa Store. All rights reserved.</p><p>Powered by<a href=\"https://www.medusajs.com\"><svg><path></path></svg></a>&amp;<a href=\"https://nextjs.org\"><svg><path></path></svg></a></p></div></div></footer></main><nextjs-portal></nextjs-portal><next-route-announcer></body>",
          "account_page": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div data-testid=\"account-page\"><div><div><div><div><div data-testid=\"login-page\"><h1>Welcome back</h1><p>Sign in to access an enhanced shopping experience.</p><form action=\"javascript:throw new Error('A React form was unexpectedly submitted. If you called form.submit() manually, consider using form.requestSubmit() instead. If you\\'re trying to use event.stopPropagation() in a submit event handler, consider also calling event.preventDefault().')\"><div><div><div><input data-testid=\"email-input\" name=\"email\" title=\"Enter a valid email address.\" type=\"email\"/><label for=\"email\">Email<span>*</span></label></div></div><div><div><input data-testid=\"password-input\" name=\"password\" type=\"password\"/><label for=\"password\">Password<span>*</span></label><button type=\"button\"><svg><path></path><path></path></svg></button></div></div></div><button data-testid=\"sign-in-button\" type=\"submit\">Sign in</button></form><span>Not a member? <button data-testid=\"register-button\">Join us</button>.</span></div></div></div></div><div><div><h3>Got questions?</h3><span>You can find frequently asked questions and answers on our customer service page.</span></div><div><a href=\"/dk/customer-service\"><p>Customer Service</p><svg><path></path></svg></a></div></div></div></div><footer><div><div><div><div><div><a href=\"/dk\">Medusa Store</a></div><div><div><span>Categories</span><ul data-testid=\"footer-categories\"><li><a data-testid=\"category-link\" href=\"/dk/categories/sweatshirts\">Sweatshirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/shirts\">Shirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/pants\">Pants</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/merch\">Merch</a><ul></ul></li></ul></div><div><span>Medusa</span><ul><li><a href=\"https://github.com/medusajs\">GitHub</a></li><li><a href=\"https://docs.medusajs.com\">Documentation</a></li><li><a href=\"https://github.com/medusajs/nextjs-starter-medusa\">Source code</a></li></ul></div></div></div><div><p>\u00a9 2025 Medusa Store. All rights reserved.</p><p>Powered by<a href=\"https://www.medusajs.com\"><svg><path></path></svg></a>&amp;<a href=\"https://nextjs.org\"><svg><path></path></svg></a></p></div></div></footer></main><nextjs-portal></nextjs-portal><next-route-announcer></body>",
          "register_form": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div data-testid=\"account-page\"><div><div><div><div><div data-testid=\"register-page\"><h1>Become a Medusa Store Member</h1><p>Create your Medusa Store Member profile, and get access to an enhanced shopping experience.</p><form action=\"javascript:throw new Error('A React form was unexpectedly submitted. If you called form.submit() manually, consider using form.requestSubmit() instead. If you\\'re trying to use event.stopPropagation() in a submit event handler, consider also calling event.preventDefault().')\"><div><div><div><input data-testid=\"first-name-input\" name=\"first_name\"/><label for=\"first_name\">First name<span>*</span></label></div></div><div><div><input data-testid=\"last-name-input\" name=\"last_name\"/><label for=\"last_name\">Last name<span>*</span></label></div></div><div><div><input data-testid=\"email-input\" name=\"email\" type=\"email\"/><label for=\"email\">Email<span>*</span></label></div></div><div><div><input data-testid=\"phone-input\" name=\"phone\" type=\"tel\"/><label for=\"phone\">Phone</label></div></div><div><div><input data-testid=\"password-input\" name=\"password\" type=\"password\"/><label for=\"password\">Password<span>*</span></label><button type=\"button\"><svg><path></path><path></path></svg></button></div></div></div><span>By creating an account, you agree to Medusa Store's <a href=\"/dk/content/privacy-policy\">Privacy Policy</a> and <a href=\"/dk/content/terms-of-use\">Terms of Use</a>.</span>