from selenium.webdriver.support.expected_conditions import presence_of_element_located, element_to_be_clickable, text_to_be_present_in_element
from selenium import webdriver
import unittest
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager