```python
import unittest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class AddToCartTest(unittest.TestCase):
    def setUp(self):
        service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=service)
        self.driver.maximize_window()
        self.base_url = "http://localhost:8000/dk"
        self.html_data = {
            "home_page": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div><div><span><h1>Ecommerce Starter Template</h1><h2>Powered by Medusa and Next.js</h2></span><a href=\"https://github.com/medusajs/nextjs-starter-medusa\"><button>View on GitHub<svg><path></path></svg></button></a></div></div><footer><div><div><div><a href=\"/dk\">Medusa Store</a></div><div><div><span>Categories</span><ul data-testid=\"footer-categories\"><li><a data-testid=\"category-link\" href=\"/dk/categories/sweatshirts\">Sweatshirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/shirts\">Shirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/pants\">Pants</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/merch\">Merch</a><ul></ul></li></ul></div><div><span>Medusa</span><ul><li><a href=\"https://github.com/medusajs\">GitHub</a></li><li><a href=\"https://docs.medusajs.com\">Documentation</a></li><li><a href=\"https://github.com/medusajs/nextjs-starter-medusa\">Source code</a></li></ul></div></div></div><div><p>\u00a9 2025 Medusa Store. All rights reserved.</p><p>Powered by<a href=\"https://www.medusajs.com\"><svg><path></path></svg></a>&amp;<a href=\"https://nextjs.org\"><svg><path></path></svg></a></p></div></div></footer></main><nextjs-portal></nextjs-portal><next-route-announcer></next-route-announcer></body>",
            "menu_opened": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div><div id=\"headlessui-popover-panel-:r0:\"><div data-testid=\"nav-menu-popup\"><div id=\"xmark\"><button data-testid=\"close-menu-button\"><svg><path></path></svg></button></div><ul><li><a data-testid=\"home-link\" href=\"/dk\">Home</a></li><li><a data-testid=\"store-link\" href=\"/dk/store\">Store</a></li><li><a data-testid=\"account-link\" href=\"/dk/account\">Account</a></li><li><a data-testid=\"cart-link\" href=\"/dk/cart\">Cart</a></li></ul><div><div><div><span><button id=\"headlessui-listbox-button-:r4:\" type=\"button\"><div><span>Shipping to:</span><span><img src=\"https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/dk.svg\"/>Denmark</span></div></button></span></div><svg><path></path></svg></div><p>\u00a9 2025 Medusa Store. All rights reserved.</p></div></div></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div><div><span><h1>Ecommerce Starter Template</h1><h2>Powered by Medusa and Next.js</h2></span><a href=\"https://github.com/medusajs/nextjs-starter-medusa\"><button>View on GitHub<svg><path></path></svg></button></a></div></div><footer><div><div><div><a href=\"/dk\">Medusa Store</a></div><div><div><span>Categories</span><ul data-testid=\"footer-categories\"><li><a data-testid=\"category-link\" href=\"/dk/categories/sweatshirts\">Sweatshirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/shirts\">Shirts</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/pants\">Pants</a><ul></ul></li><li><a data-testid=\"category-link\" href=\"/dk/categories/merch\">Merch</a><ul></ul></li></ul></div><div><span>Medusa</span><ul><li><a href=\"https://github.com/medusajs\">GitHub</a></li><li><a href=\"https://docs.medusajs.com\">Documentation</a></li><li><a href=\"https://github.com/medusajs/nextjs-starter-medusa\">Source code</a></li></ul></div></div></div><div><p>\u00a9 2025 Medusa Store. All rights reserved.</p><p>Powered by<a href=\"https://www.medusajs.com\"><svg><path></path></svg></a>&amp;<a href=\"https://nextjs.org\"><svg><path></path></svg></a></p></div></div></footer></main><nextjs-portal></nextjs-portal><next-route-announcer></next-route-announcer></body>",
            "store_page": "<body><main><div><header><nav><div><div><div><div><div><div><button data-testid=\"nav-menu-button\" id=\"headlessui-popover-button-:R6qdtt7:\" type=\"button\">Menu</button></div></div></div></div></div></div><div><a data-testid=\"nav-store-link\" href=\"/dk\">Medusa Store</a></div><div><div><a data-testid=\"nav-account-link\" href=\"/dk/account\">Account</a></div><div><div><button id=\"headlessui-popover-button-:Rrmdtt7:\" type=\"button\"><a data-testid=\"nav-cart-link\" href=\"/dk/cart\">Cart (0)</a></button></div></div></div></nav></header></div><div data-testid=\"category-container\"><div><div><p>Sort by</p><div><div><svg><circle></circle></svg><button id=\"created_at\" type=\"button\" value=\"created_at\"></button><label data-testid=\"radio-label\" for=\"created_at\">Latest Arrivals</label></div><div><button id=\"price_asc\" type=\"button\" value=\"price_asc\"></button><label data-testid=\"radio-label\" for=\"price_asc\">Price: Low -&gt; High</label></div><div><button id=\"price_desc\" type=\"button\" value=\"price_desc\"></button><label data-testid=\"radio-label\" for=\"price_desc\">Price: High -&gt; Low</label></div></div></div></div><div><div><h1 data-testid=\"store-page-title\">All products</h1></div><ul data-testid=\"products-list\"><li><a href=\"/dk/products/sweatshirt\"><div data-testid=\"product-wrapper\"><div><img alt=\"Thumbnail\" src=\"/_next/image?url=https%3A%2F%2Fmedusa-public-images.s3.eu-west-1.amazonaws.com%2Fsweatshirt-vintage-front.png&amp;w=3840&amp;q=50\"/></div><div><p data-testid=\"product-title\">Medusa Sweatshirt</p><div><p data-testid=\"price\">\u20ac10.00</p></div></div></div></a></li><li><a href