```python
import unittest
import random
import string

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.common.keys import Keys


class CheckoutTest(unittest.TestCase):

    def setUp(self):
        self.driver: WebDriver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        self.driver.maximize_window()
        self.base_url = "http://max/"
        self.html_data = {
            "home": "<body style=\"zoom: 50%;\"> <div class=\"master-wrapper-page\"> <div class=\"header\"> <a class=\"skip\" href=\"#main\">Skip navigation</a> <div class=\"header-upper\"> <div class=\"header-links-wrapper\"> <div class=\"flyout-cart\" id=\"flyout-cart\"> <div class=\"mini-shopping-cart\"> <div class=\"count\"> You have no items in your shopping cart. </div> </div> </div> </div> </div> <div class=\"header-lower\"> <div class=\"header-logo\"> <a href=\"/\"> <img alt=\"Your store name\" src=\"http://max/Themes/DefaultClean/Content/images/logo.png\" title=\"\"/> </a> </div> <div class=\"search-box store-search-box\"> <form action=\"/search\" id=\"small-search-box-form\" method=\"get\"> <input aria-label=\"Search store\" autocomplete=\"off\" class=\"search-box-text ui-autocomplete-input\" id=\"small-searchterms\" name=\"q\" placeholder=\"Search store\" type=\"text\"/> <button class=\"button-1 search-box-button\" type=\"submit\">Search</button> </form> </div> </div> </div> <div class=\"header-menu\"> <ul class=\"top-menu notmobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> <div aria-controls=\"aria-categories-mobile-ul\" class=\"menu-toggle\" role=\"button\" tabindex=\"0\">Menu</div> <ul class=\"top-menu mobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> </div> </div> </body>",
            "search_page": "<body style=\"zoom: 50%;\"> <div class=\"master-wrapper-page\"> <div class=\"header\"> <a class=\"skip\" href=\"#main\">Skip navigation</a> <div class=\"header-upper\"> <div class=\"header-links-wrapper\"> <div class=\"flyout-cart\" id=\"flyout-cart\"> <div class=\"mini-shopping-cart\"> <div class=\"count\"> You have no items in your shopping cart. </div> </div> </div> </div> </div> <div class=\"header-lower\"> <div class=\"header-logo\"> <a href=\"/\"> <img alt=\"Your store name\" src=\"http://max/Themes/DefaultClean/Content/images/logo.png\" title=\"\"/> </a> </div> <div class=\"search-box store-search-box\"> <form action=\"/search\" id=\"small-search-box-form\" method=\"get\"> <input aria-label=\"Search store\" autocomplete=\"off\" class=\"search-box-text ui-autocomplete-input\" id=\"small-searchterms\" name=\"q\" placeholder=\"Search store\" type=\"text\"/> <button class=\"button-1 search-box-button\" type=\"submit\">Search</button> </form> </div> </div> </div> <div class=\"header-menu\"> <ul class=\"top-menu notmobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> <div aria-controls=\"aria-categories-mobile-ul\" class=\"menu-toggle\" role=\"button\" tabindex=\"0\">Menu</div> <ul class=\"top-menu mobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> </div> <div class=\"master-wrapper-content\" id=\"main\" role=\"main\"> <div class=\"master-column-wrapper\"> <div class=\"center-2\"> <div class=\"page search-page\"> <div class=\"page-title\"> <h1>Search</h1> </div> <div class=\"page-body\"> <div class=\"search-input\"> <form action=\"/search\" method=\"get\" novalidate=\"novalidate\"> <div class=\"fieldset\"> <div class=\"form-fields\"> <div class=\"basic-search\"> <div class=\"inputs\"> <label for=\"q\">Search keyword:</label> <input class=\"search-text\" id=\"q\" name=\"q\" type=\"text\" value=\"\"/> </div> <div class=\"inputs reversed\"> <input data-val=\"true\" data-val-required=\"The Advanced search field is required.\" id=\"advs\" name=\"advs\" type=\"checkbox\" value=\"true\"/> <label for=\"advs\">Advanced search</label> </div> </div> </div> </div> <div class=\"buttons\"> <button class=\"button-1 search-button\" type=\"submit\">Search</button> </div> </form> </div> </div> </div> </div> </div> </div> </div> </body>",
            "search_results": "<body style=\"zoom: 50%;\"> <div class=\"master-wrapper-page\"> <div class=\"header\"> <a class=\"skip\" href=\"#main\">Skip navigation</a> <div class=\"header-upper\"> <div class=\"header-links-wrapper\"> <div class=\"flyout-cart\" id=\"flyout-cart\"> <div class=\"mini-shopping-cart\"> <div class=\"count\"> You have no items in your shopping cart. </div> </div> </div> </div> </div> <div class=\"header-lower\"> <div class=\"header-logo\"> <a href=\"/\"> <img alt=\"Your store name\" src=\"http://max/Themes/DefaultClean/Content/images/logo.png\" title=\"\"/> </a> </div> <div class=\"search-box store-search-box\"> <form action=\"/search\" id=\"small-search-box-form\" method=\"get\"> <input aria-label=\"Search store\" autocomplete=\"off\" class=\"search-box-text ui-autocomplete-input\" id=\"small-searchterms\" name=\"q\" placeholder=\"Search store\" type=\"text\"/> <button class=\"button-1 search-box-button\" type=\"submit\">Search</button> </form> </div> </div> </div> <div class=\"header-menu\"> <ul class=\"top-menu notmobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> <div aria-controls=\"aria-categories-mobile-ul\" class=\"menu-toggle\" role=\"button\" tabindex=\"0\">Menu</div> <ul class=\"top-menu mobile\"> <li><a href=\"/\">Home page</a></li> <li><a href=\"/newproducts\">New products</a></li> <li><a href=\"/search\">Search</a></li> <li><a href=\"/customer/info\">My account</a></li> <li><a href=\"/blog\">Blog</a></li> <li><a href=\"/contactus\">Contact us</a></li> </ul> </div> <div class=\"master-wrapper-content\" id=\"main\" role=\"main\"> <div class=\"master-column-wrapper\"> <div class=\"side-2\"> <div class=\"block product-filters\"> <div class=\"product-filter price-range-filter\"> <div class=\"filter-title\"> <strong>Filter by price</strong> </div> <div class=\"filter-content\"> <div class=\"selected-price-range\"> <span